# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: yosuke.saito
email: yosuke.saito1202@gmail.com
description: This is Yosuke Saito's blog & portfolio site.
keywords: Programming,Web,AI,Machine Learning,saitoxu,Yosuke Saito,斎藤,斎藤陽介
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://saitoxu.io" # the base hostname & protocol for your site
# url: "http://127.0.0.1:4000"
twitter_username: saitoxu
github_username:  saitoxu

# Build settings
markdown: kramdown
theme: minima

# pagination
gems: [jekyll-paginate]
paginate: 5

kramdown:
  syntax_highlighter: rouge

exclude: [vendor]
